/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/_index'

// Create Virtual Routes

const SignupLazyImport = createFileRoute('/signup')()
const SigninLazyImport = createFileRoute('/signin')()
const PostsLazyImport = createFileRoute('/posts')()
const FiltersLazyImport = createFileRoute('/filters')()
const AboutLazyImport = createFileRoute('/about')()
const IndexMapLazyImport = createFileRoute('/_index/map')()
const IndexHomeLazyImport = createFileRoute('/_index/home')()

// Create/Update Routes

const SignupLazyRoute = SignupLazyImport.update({
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/signup.lazy').then((d) => d.Route))

const SigninLazyRoute = SigninLazyImport.update({
  path: '/signin',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/signin.lazy').then((d) => d.Route))

const PostsLazyRoute = PostsLazyImport.update({
  path: '/posts',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/posts.lazy').then((d) => d.Route))

const FiltersLazyRoute = FiltersLazyImport.update({
  path: '/filters',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/filters.lazy').then((d) => d.Route))

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexRoute = IndexImport.update({
  id: '/_index',
  getParentRoute: () => rootRoute,
} as any)

const IndexMapLazyRoute = IndexMapLazyImport.update({
  path: '/map',
  getParentRoute: () => IndexRoute,
} as any).lazy(() => import('./routes/_index.map.lazy').then((d) => d.Route))

const IndexHomeLazyRoute = IndexHomeLazyImport.update({
  path: '/home',
  getParentRoute: () => IndexRoute,
} as any).lazy(() => import('./routes/_index.home.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_index': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/filters': {
      preLoaderRoute: typeof FiltersLazyImport
      parentRoute: typeof rootRoute
    }
    '/posts': {
      preLoaderRoute: typeof PostsLazyImport
      parentRoute: typeof rootRoute
    }
    '/signin': {
      preLoaderRoute: typeof SigninLazyImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      preLoaderRoute: typeof SignupLazyImport
      parentRoute: typeof rootRoute
    }
    '/_index/home': {
      preLoaderRoute: typeof IndexHomeLazyImport
      parentRoute: typeof IndexImport
    }
    '/_index/map': {
      preLoaderRoute: typeof IndexMapLazyImport
      parentRoute: typeof IndexImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute.addChildren([IndexHomeLazyRoute, IndexMapLazyRoute]),
  AboutLazyRoute,
  FiltersLazyRoute,
  PostsLazyRoute,
  SigninLazyRoute,
  SignupLazyRoute,
])

/* prettier-ignore-end */
